In [2]:
import pandas as pd
import matplotlib.pyplot as plt


countries = pd.read_csv('countries.csv')
income = pd.read_excel('indicator gapminder gdp_per_capita_ppp.xlsx', index_col=0).transpose()
income

gdp pc test,Abkhazia,Afghanistan,Akrotiri and Dhekelia,Albania,Algeria,American Samoa,Andorra,Angola,Anguilla,Antigua and Barbuda,...,Western Sahara,Vietnam,Virgin Islands (U.S.),Yemen Arab Republic (Former),Yemen Democratic (Former),"Yemen, Rep.",Yugoslavia,Zambia,Zimbabwe,Åland
1800,NaN,472.0535,NaN,601.215222,766.253664,674.453726,1260.123256,359.932582,775.668711,538.376199,...,NaN,459.708986,NaN,NaN,NaN,661.902376,NaN,364.464811,372.818338,NaN
1801,NaN,472.0535,NaN,601.839631,766.234779,674.453726,1262.214402,359.932582,775.668711,538.376199,...,NaN,459.708986,NaN,NaN,NaN,662.058563,NaN,364.464811,372.818338,NaN
1802,NaN,472.0535,NaN,602.464688,766.215895,674.453726,1264.309018,359.932582,775.668711,538.376199,...,NaN,459.708986,NaN,NaN,NaN,662.214787,NaN,364.464811,372.818338,NaN
1803,NaN,472.0535,NaN,603.090394,766.197011,674.453726,1266.407109,359.932582,775.668711,538.376199,...,NaN,459.708986,NaN,NaN,NaN,662.371047,NaN,364.464811,372.818338,NaN
1804,NaN,472.0535,NaN,603.716751,766.178127,674.453726,1268.508683,359.932582,775.668711,538.376199,...,NaN,459.708986,NaN,NaN,NaN,662.527345,NaN,364.464811,372.818338,NaN

In [52]:
income

Country,Abkhazia,Afghanistan,Akrotiri and Dhekelia,Albania,Algeria,American Samoa,Andorra,Angola,Anguilla,Antigua and Barbuda,...,Western Sahara,Vietnam,Virgin Islands (U.S.),Yemen Arab Republic (Former),Yemen Democratic (Former),"Yemen, Rep.",Yugoslavia,Zambia,Zimbabwe,Åland
1800,NaN,472.053500,NaN,601.215222,766.253664,674.453726,1260.123256,359.932582,775.668711,538.376199,...,NaN,459.708986,NaN,NaN,NaN,661.902376,NaN,364.464811,372.818338,NaN
1801,NaN,472.053500,NaN,601.839631,766.234779,674.453726,1262.214402,359.932582,775.668711,538.376199,...,NaN,459.708986,NaN,NaN,NaN,662.058563,NaN,364.464811,372.818338,NaN
1802,NaN,472.053500,NaN,602.464688,766.215895,674.453726,1264.309018,359.932582,775.668711,538.376199,...,NaN,459.708986,NaN,NaN,NaN,662.214787,NaN,364.464811,372.818338,NaN
1803,NaN,472.053500,NaN,603.090394,766.197011,674.453726,1266.407109,359.932582,775.668711,538.376199,...,NaN,459.708986,NaN,NaN,NaN,662.371047,NaN,364.464811,372.818338,NaN
1804,NaN,472.053500,NaN,603.716751,766.178127,674.453726,1268.508683,359.932582,775.668711,538.376199,...,NaN,459.708986,NaN,NaN,NaN,662.527345,NaN,364.464811,372.818338,NaN
1805,NaN,472.053500,NaN,604.343757,766.159244,674.453726,1270.613744,359.932582,775.668711,538.376199,...,NaN,459.708986,NaN,NaN,NaN,662.683680,NaN,364.464811,372.818338,NaN
1806,NaN,472.053500,NaN,604.971415,766.140362,674.453726,1272.722298,359.932582,775.668711,538.376199,...,NaN,459.708986,NaN,NaN,NaN,662.840051,NaN,364.464811,372.818338,NaN
1807,NaN,472.053500,NaN,605.599725,766.121480,674.453726,1274.834351,359.932582,775.668711,538.376199,...,NaN,459.708986,NaN,NaN,NaN,662.996459,NaN,364.464811,372.818338,NaN
1808,NaN,472.053500,NaN,606.228687,766.102598,674.453726,1276.949910,359.932582,775.668711,538.376199,...,NaN,459.708986,NaN,NaN,NaN,663.152904,NaN,364.464811,372.818338,NaN
1809,NaN,472.053500,NaN,606.858303,766.083717,674.453726,1279.068979,359.932582,775.668711,538.376199,...,NaN,459.708986,NaN,NaN,NaN,663.309387,NaN,364.464811,372.818338,NaN
1810,NaN,472.053500,NaN,607.488572,766.064836,674.453726,1281.191564,359.932582,775.668711,538.376199,...,NaN,459.708986,NaN,NaN,NaN,663.465906,NaN,364.464811,372.818338,NaN
1811,NaN,472.053500,NaN,608.119496,766.045956,674.453726,1283.317672,359.932582,775.668711,538.376199,...,NaN,459.708986,NaN,NaN,NaN,663.622462,NaN,364.464811,372.818338,NaN
1812,NaN,472.053500,NaN,608.751075,766.027076,674.453726,1285.447308,359.932582,775.668711,538.376199,...,NaN,459.708986,NaN,NaN,NaN,663.779054,NaN,364.464811,372.818338,NaN
1813,NaN,472.053500,NaN,609.383311,766.008197,674.453726,1287.580478,359.932582,775.668711,538.376199,...,NaN,459.708986,NaN,NaN,NaN,663.935684,NaN,364.464811,372.818338,NaN
1814,NaN,472.053500,NaN,610.016202,765.989318,674.453726,1289.717189,359.932582,775.668711,538.376199,...,NaN,459.708986,NaN,NaN,NaN,664.092351,NaN,364.464811,372.818338,NaN
1815,NaN,472.053500,NaN,610.649752,765.970439,674.453726,1291.857445,359.932582,775.668711,538.376199,...,NaN,459.708986,NaN,NaN,NaN,664.249055,NaN,364.464811,372.818338,NaN
1816,NaN,472.053500,NaN,611.283959,765.951561,674.453726,1294.001252,359.932582,775.668711,538.376199,...,NaN,459.708986,NaN,NaN,NaN,664.405796,NaN,364.464811,372.818338,NaN
1817,NaN,472.053500,NaN,611.918825,765.932684,674.453726,1296.148618,359.932582,775.668711,538.376199,...,NaN,459.708986,NaN,NaN,NaN,664.562573,NaN,364.464811,372.818338,NaN
1818,NaN,472.053500,NaN,612.554350,765.913807,674.453726,1298.299546,359.932582,775.668711,538.376199,...,NaN,459.708986,NaN,NaN,NaN,664.719388,NaN,364.464811,372.818338,NaN
1819,NaN,472.053500,NaN,613.190535,765.894930,674.453726,1300.454045,359.932582,775.668711,538.376199,...,NaN,459.708986,NaN,NaN,NaN,664.876240,NaN,364.464811,372.818338,NaN
1820,NaN,472.053500,NaN,613.827381,765.876054,674.453726,1302.612118,359.932582,775.668711,538.376199,...,NaN,459.708986,NaN,NaN,NaN,665.033129,NaN,364.464811,372.818338,NaN
1821,NaN,473.588078,NaN,615.133804,773.695865,676.643976,1317.903699,361.620340,780.794194,541.933695,...,NaN,459.322966,NaN,NaN,NaN,665.791939,NaN,366.173820,372.974628,NaN
1822,NaN,475.127644,NaN,616.443007,781.595518,678.841338,1333.374790,363.316011,785.953546,545.514699,...,NaN,458.937271,NaN,NaN,NaN,666.551616,NaN,367.890844,373.130984,NaN
1823,NaN,476.672216,NaN,617.754997,789.575828,681.045836,1349.027499,365.019634,791.146991,549.119365,...,NaN,458.551900,NaN,NaN,NaN,667.312159,NaN,369.615919,373.287405,NaN
1824,NaN,478.221809,NaN,619.069779,797.637620,683.257493,1364.863957,366.731246,796.374752,552.747850,...,NaN,458.166852,NaN,NaN,NaN,668.073570,NaN,371.349083,373.443892,NaN
1825,NaN,479.776439,NaN,620.387359,805.781725,685.476333,1380.886323,368.450883,801.637058,556.400312,...,NaN,457.782128,NaN,NaN,NaN,668.835850,NaN,373.090373,373.600445,NaN
1826,NaN,481.336123,NaN,621.707744,814.008983,687.702378,1397.096777,370.178584,806.934136,560.076908,...,NaN,457.397726,NaN,NaN,NaN,669.599000,NaN,374.839829,373.757063,NaN
1827,NaN,482.900878,NaN,623.030939,822.320245,689.935652,1413.497529,371.914386,812.266216,563.777799,...,NaN,457.013648,NaN,NaN,NaN,670.363020,NaN,376.597489,373.913747,NaN
1828,NaN,484.470719,NaN,624.356950,830.716366,692.176178,1430.090812,373.658328,817.633530,567.503144,...,NaN,456.629891,NaN,NaN,NaN,671.127912,NaN,378.363390,374.070497,NaN
1829,NaN,486.045663,NaN,625.685783,839.198214,694.423980,1446.878887,375.410447,823.036310,571.253106,...,NaN,456.246458,NaN,NaN,NaN,671.893677,NaN,380.137571,374.227312,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1983,NaN,1013.132736,NaN,3652.076174,5853.656218,6408.770283,26568.202079,2584.557046,8015.966179,6453.088079,...,NaN,729.505016,NaN,NaN,NaN,2032.190358,NaN,1329.497993,771.843260,NaN
1984,NaN,994.571244,NaN,3672.867539,5986.542038,6421.349460,25820.298638,2527.467914,8263.647120,7024.111407,...,NaN,777.061359,NaN,NaN,NaN,2050.332377,NaN,1279.198766,728.371344,NaN
1985,NaN,961.924185,NaN,3692.089631,6107.181013,6433.953328,25465.804921,2492.832132,8975.705788,7693.923848,...,NaN,805.218820,NaN,NaN,NaN,1973.815130,NaN,1258.788760,749.908751,NaN
1986,NaN,1030.888067,NaN,3715.549706,5876.048095,6446.581935,25621.537279,2220.605332,9911.093649,8513.743698,...,NaN,809.926033,NaN,NaN,NaN,1955.752751,NaN,1223.735344,742.303597,NaN
1987,NaN,852.395945,NaN,3738.932735,5681.358539,6459.235329,26576.000801,2430.208311,10604.348076,9474.137689,...,NaN,820.799445,NaN,NaN,NaN,1971.741538,NaN,1213.315116,706.157306,NaN
1988,NaN,770.010794,NaN,3762.606544,5415.986264,6471.913560,27517.713607,2728.529902,11605.744183,10425.226898,...,NaN,851.423952,NaN,NaN,NaN,1989.886490,NaN,1249.787665,744.458975,NaN
1989,NaN,751.441274,NaN,3790.981701,5457.745569,6484.616675,28281.893393,2730.558884,12220.769111,11211.438865,...,NaN,868.799373,NaN,NaN,NaN,1991.575551,NaN,1226.430900,768.278533,NaN
1990,NaN,709.504942,NaN,3824.847995,5244.509612,6497.344724,28511.183263,2777.417631,12335.014460,11573.561437,...,NaN,893.884758,NaN,NaN,NaN,1923.299759,NaN,1299.991125,761.502579,NaN
1991,NaN,705.445799,NaN,2717.568290,5061.303464,6604.364154,28091.122478,2730.854238,11709.287087,11751.602262,...,NaN,927.114196,NaN,NaN,NaN,1859.237877,NaN,1264.807358,782.088367,NaN
1992,NaN,649.341395,NaN,2497.437901,5023.216647,6713.146327,27041.017125,2627.845685,12197.826496,11677.353613,...,NaN,989.023149,NaN,NaN,NaN,1879.496673,NaN,1210.884633,693.420786,NaN
1993,NaN,558.853241,NaN,2716.646193,4800.317117,6823.720280,25514.038520,1869.923753,12770.834760,12036.981411,...,NaN,1049.363562,NaN,NaN,NaN,1861.888827,NaN,1261.302462,686.671313,NaN
1994,NaN,500.449447,NaN,2918.816698,4652.841153,6936.115525,25092.432702,1851.446270,13477.415886,12477.548689,...,NaN,1121.672680,NaN,NaN,NaN,1834.922240,NaN,1067.932935,719.986723,NaN
1995,NaN,601.874210,NaN,3285.534735,4732.433000,7050.362060,25063.769055,1989.024681,12888.093770,11650.356091,...,NaN,1208.143068,NaN,NaN,NaN,1970.601490,NaN,1017.791739,717.360429,NaN
1996,NaN,617.910636,NaN,3569.594506,4824.212475,7166.490380,25839.065059,2157.352097,12957.806543,12104.520511,...,NaN,1300.380849,NaN,NaN,NaN,2022.928452,NaN,1060.554879,781.496598,NaN
1997,NaN,635.341351,NaN,3193.054604,4797.295051,7284.531479,28057.471362,2277.140884,14096.128268,12387.280722,...,NaN,1385.896769,NaN,NaN,NaN,2117.484526,NaN,1071.353818,792.449960,NaN
1998,NaN,653.296853,NaN,3584.773197,4965.228361,7404.516863,28982.138216,2384.479259,15298.768825,12613.159934,...,NaN,1445.953125,NaN,NaN,NaN,2149.796644,NaN,1027.229083,806.314017,NaN
1999,NaN,670.987221,NaN,3928.275138,5048.615566,7526.478557,30144.971656,2417.181021,15611.946138,12826.309853,...,NaN,1495.628979,NaN,NaN,NaN,2158.603036,NaN,1025.583049,792.759184,NaN
2000,NaN,663.909878,NaN,4195.210368,5098.853564,7650.449113,30265.941054,2446.645873,15551.725642,12738.744631,...,NaN,1577.531777,NaN,NaN,NaN,2217.073804,NaN,1035.903578,745.768974,NaN
2001,NaN,595.038741,NaN,4476.045166,5156.447405,7776.461620,33293.000527,2479.690229,15678.672073,12770.739252,...,NaN,1666.507033,NaN,NaN,NaN,2225.103568,NaN,1059.726572,719.963252,NaN
2002,NaN,726.734055,NaN,4604.211737,5288.040382,8200.790273,34485.483523,2773.287312,15179.260049,12874.342595,...,NaN,1764.456677,NaN,NaN,NaN,2234.820827,NaN,1071.613938,672.038623,NaN
2003,NaN,785.127571,NaN,4855.210024,5576.851564,8648.272748,35925.278283,2785.393957,15300.111536,13346.281640,...,NaN,1872.133959,NaN,NaN,NaN,2239.828224,NaN,1105.234654,598.242101,NaN
2004,NaN,804.717458,NaN,5115.252837,5790.967692,9120.172450,37427.606316,3007.114595,18278.821179,14114.091502,...,NaN,1996.869216,NaN,NaN,NaN,2250.897567,NaN,1140.764902,571.743059,NaN
2005,NaN,874.000000,NaN,5369.000000,6011.000000,9617.821726,39002.409829,3533.000000,19478.900965,14579.000000,...,NaN,2142.000000,NaN,NaN,NaN,2276.000000,NaN,1175.000000,538.000000,NaN
2006,NaN,887.914578,NaN,5652.049321,6022.270940,11295.558770,39924.837176,4148.002450,22716.054804,16223.389123,...,NaN,2289.340579,NaN,NaN,NaN,2277.838915,NaN,1218.964755,520.168581,NaN
2007,NaN,983.652314,NaN,5958.021197,6133.782763,13265.961001,39244.406089,4950.178553,25037.546990,17161.686260,...,NaN,2453.801665,NaN,NaN,NaN,2283.391979,NaN,1263.450627,499.683553,NaN
2008,NaN,984.805841,NaN,6365.530359,6162.719840,NaN,37046.502702,5488.457748,24145.373823,17226.580703,...,NaN,2577.732510,NaN,NaN,NaN,2295.806170,NaN,1302.859270,408.134473,NaN
2009,NaN,1154.859365,NaN,6550.896164,6173.729741,NaN,34710.214013,5475.945894,19309.746902,15219.499977,...,NaN,2682.750193,NaN,NaN,NaN,2313.157376,NaN,1352.522232,441.142789,NaN
2010,NaN,1214.613653,NaN,6746.445312,6300.648214,NaN,33052.282318,5497.618103,18220.478248,13921.516220,...,NaN,2830.775700,NaN,NaN,NaN,2418.761076,NaN,1420.231814,479.824780,NaN
2011,NaN,1261.354184,NaN,6914.267317,6354.640523,NaN,31630.742845,5546.646572,18600.583675,13508.802607,...,NaN,2961.834605,NaN,NaN,NaN,2102.216461,NaN,1480.686307,526.332686,NaN
2012,NaN,1349.696941,NaN,6969.306283,6419.127829,NaN,NaN,5838.155376,NaN,13722.986163,...,NaN,3073.649612,NaN,NaN,NaN,2043.787776,NaN,1550.923859,545.344601,NaN

In [46]:
year_data = income.loc[1999].to_frame('Income')
year_data.index.names = ['Country']
result = countries.join(year_data, on = ['Country'], how = 'right', lsuffix='_x')

In [51]:
result.hist('Income', by='Region')
plt.savefig('box_' + str(1999) + '.pdf')

In [27]:
year_data.index.names = ['Country']

In [43]:
countries.join(year_data, on = ['Country'], how = 'right', lsuffix='_x')

                          Country  Region        Income
0                         Algeria  AFRICA   5048.615566
1                          Angola  AFRICA   2417.181021
2                           Benin  AFRICA   1272.796464
3                        Botswana  AFRICA   9416.670376
5                         Burundi  AFRICA    455.412096
6                        Cameroon  AFRICA   1770.650380
7                      Cape Verde  AFRICA   2168.686778
9                            Chad  AFRICA   1039.290389
10                        Comoros  AFRICA   1137.887465
13                       Djibouti  AFRICA   1901.116370
14                          Egypt  AFRICA   4482.937530
15              Equatorial Guinea  AFRICA   4623.257066
16                        Eritrea  AFRICA    877.606630
17                       Ethiopia  AFRICA    496.867976
18                          Gabon  AFRICA  13276.449872
19                         Gambia  AFRICA    672.495994
20                          Ghana  AFRICA   1052.282225
21                         Guinea  AFRICA    909.938795
22                  Guinea-Bissau  AFRICA    590.703138
24                          Kenya  AFRICA   1346.864615
25                        Lesotho  AFRICA   1153.297561
26                        Liberia  AFRICA    529.793062
27                          Libya  AFRICA   8966.926165
28                     Madagascar  AFRICA   1010.139648
29                         Malawi  AFRICA    705.875174
30                           Mali  AFRICA    844.114837
31                     Mauritania  AFRICA   1510.808087
32                      Mauritius  AFRICA   8149.824766
33                        Morocco  AFRICA   3097.016457
34                     Mozambique  AFRICA    545.803972
..                            ...     ...           ...
193                      Pitcairn     NaN           NaN
193                   Puerto Rico     NaN  18084.730519
193                       Reunion     NaN   6058.561889
193                        Russia     NaN   7757.866564
193              Saint Barthélemy     NaN           NaN
193                  Saint Helena     NaN   2326.485099
193                  Saint Martin     NaN           NaN
193      Saint-Pierre-et-Miquelon     NaN           NaN
193         Serbia and Montenegro     NaN           NaN
193       Serbia excluding Kosovo     NaN           NaN
193               Slovak Republic     NaN  12600.772180
193                    Somaliland     NaN           NaN
193                 South Ossetia     NaN           NaN
193                      Svalbard     NaN           NaN
193                        Taiwan     NaN  22477.708371
193                   Timor-Leste     NaN   2442.672279
193                       Tokelau     NaN           NaN
193                  Transnistria     NaN           NaN
193      Turks and Caicos Islands     NaN  26822.433245
193                          USSR     NaN           NaN
193              Wallis et Futuna     NaN   2826.724657
193            West Bank and Gaza     NaN   7864.939289
193                  West Germany     NaN           NaN
193                Western Sahara     NaN           NaN
193         Virgin Islands (U.S.)     NaN           NaN
193  Yemen Arab Republic (Former)     NaN           NaN
193     Yemen Democratic (Former)     NaN           NaN
193                   Yemen, Rep.     NaN   2158.603036
193                    Yugoslavia     NaN           NaN
193                         Åland     NaN           NaN

[260 rows x 3 columns]